// health-hub-online-main/src/components/DoctorAIInsights.tsx
import { useState } from "react";
import { Sparkles, Loader2, AlertCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";

interface Doctor {
  id: string;
  name: string;
  specialty: string;
  hospital: string;
  experience: string;
  rating: number;
  reviews: number;
  qualifications?: string[];
  location: string;
  fee?: string;
}

interface DoctorAIInsightsProps {
  doctor: Doctor;
}

const DoctorAIInsights = ({ doctor }: DoctorAIInsightsProps) => {
  const [insights, setInsights] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const { toast } = useToast();

  const fetchInsights = async () => {
    setIsLoading(true);
    setError(null);

    try {
      const { data, error: fnError } = await supabase.functions.invoke("doctor-ai-insights", {
        body: { doctor }
      });

      if (fnError) {
        throw fnError;
      }

      if (data?.error) {
        throw new Error(data.error);
      }

      setInsights(data.insights);
    } catch (err) {
      console.error("Error fetching AI insights:", err);
      const errorMessage = err instanceof Error ? err.message : "Failed to get AI insights";
      setError(errorMessage);
      toast({
        title: "Error",
        description: errorMessage,
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="card-premium p-6">
      <div className="flex items-center justify-between mb-4">
        <h2 className="font-display font-bold text-xl text-foreground flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-primary" />
          AI Insights
        </h2>
        {!insights && !isLoading && (
          <Button 
            onClick={fetchInsights} 
            variant="outline" 
            size="sm"
            className="gap-2"
          >
            <Sparkles className="w-4 h-4" />
            Generate Insights
          </Button>
        )}
      </div>

      {isLoading && (
        <div className="flex items-center justify-center py-12">
          <div className="text-center">
            <Loader2 className="w-8 h-8 animate-spin text-primary mx-auto mb-3" />
            <p className="text-muted-foreground text-sm">Analyzing doctor profile...</p>
          </div>
        </div>
      )}

      {error && !isLoading && (
        <div className="flex items-center gap-3 p-4 bg-destructive/10 rounded-xl text-destructive">
          <AlertCircle className="w-5 h-5 flex-shrink-0" />
          <div>
            <p className="font-medium">Unable to generate insights</p>
            <p className="text-sm opacity-80">{error}</p>
            <Button 
              onClick={fetchInsights} 
              variant="outline" 
              size="sm" 
              className="mt-2"
            >
              Try Again
            </Button>
          </div>
        </div>
      )}

      {insights && !isLoading && (
        <div className="space-y-4">
          <div className="prose prose-sm max-w-none text-muted-foreground">
            {insights.split('\n').map((paragraph, idx) => (
              paragraph.trim() && (
                <p key={idx} className="leading-relaxed mb-3">
                  {paragraph}
                </p>
              )
            ))}
          </div>
          <div className="pt-4 border-t border-border">
            <p className="text-xs text-muted-foreground flex items-center gap-1">
              <Sparkles className="w-3 h-3" />
              AI-generated insights based on doctor profile
            </p>
          </div>
        </div>
      )}

      {!insights && !isLoading && !error && (
        <div className="text-center py-8 text-muted-foreground">
          <Sparkles className="w-12 h-12 mx-auto mb-3 opacity-30" />
          <p className="text-sm">Click "Generate Insights" to get AI-powered analysis</p>
          <p className="text-xs mt-1 opacity-70">Learn why this doctor might be right for you</p>
        </div>
      )}
    </div>
  );
};

export default DoctorAIInsights;

// app/components/DoctorAIInsights.vue
<script setup lang="ts">
import { ref } from "vue";
import type { Doctor } from "~/utils/doctors";

const props = defineProps<{
    doctor: Doctor
}>();

const { doctor } = props;

const insights = ref<string | null>(null);
const isLoading = ref(false);
const error = ref<string | null>(null);

// Mock implementation since we don't have the backend function yet
const fetchInsights = async () => {
    isLoading.value = true;
    error.value = null;

    try {
        // Simulate API delay
        await new Promise(resolve => setTimeout(resolve, 2000));

        // Mock AI response based on doctor data
        insights.value = `Based on Dr. ${doctor.name}'s profile:\n\n` +
            `1. **Expertise Match**: With ${doctor.experience} of experience in ${doctor.specialty}, Dr. ${doctor.name} is highly qualified for patients seeking specialized homeopathic care.\n\n` +
            `2. **Patient Satisfaction**: A ${doctor.rating}/5 rating from ${doctor.reviews} reviews indicates consistent high-quality care and patient trust.\n\n` +
            `3. **Accessibility**: Located in ${doctor.hospital}, ${doctor.location}, making it convenient for local patients.\n\n` +
            `4. **Professional Standing**: Holds reputable qualifications (${doctor.qualifications?.join(", ") || 'Verified credentials'}), ensuring standardized medical practices.`;

    } catch (err: any) {
        console.error("Error fetching AI insights:", err);
        error.value = "Failed to generate insights. Please try again.";
    } finally {
        isLoading.value = false;
    }
};
</script>

<template>
    <div class="card-premium p-6">
        <div class="flex items-center justify-between mb-4">
            <h2 class="font-display font-bold text-xl text-foreground flex items-center gap-2">
                <UIcon name="i-lucide-sparkles" class="w-5 h-5 text-primary" />
                AI Insights
            </h2>
            <UButton v-if="!insights && !isLoading" @click="fetchInsights" variant="outline" size="sm" class="gap-2">
                <UIcon name="i-lucide-sparkles" class="w-4 h-4" />
                Generate Insights
            </UButton>
        </div>

        <div v-if="isLoading" class="flex flex-col items-center justify-center py-12">
            <UIcon name="i-lucide-loader-2" class="w-8 h-8 animate-spin text-primary mb-3" />
            <p class="text-muted-foreground text-sm">Analyzing doctor profile...</p>
        </div>

        <div v-if="error && !isLoading"
            class="flex items-start gap-3 p-4 bg-destructive/10 rounded-xl text-destructive">
            <UIcon name="i-lucide-alert-circle" class="w-5 h-5 flex-shrink-0 mt-0.5" />
            <div>
                <p class="font-medium">Unable to generate insights</p>
                <p class="text-sm opacity-80">{{ error }}</p>
                <UButton @click="fetchInsights" variant="outline" size="sm" class="mt-2">
                    Try Again
                </UButton>
            </div>
        </div>

        <div v-if="insights && !isLoading" class="space-y-4">
            <div class="prose prose-sm max-w-none text-muted-foreground">
                <div v-for="(paragraph, idx) in insights.split('\n')" :key="idx" class="mb-3">
                    <p v-if="paragraph.trim()" class="leading-relaxed">
                        {{ paragraph }}
                    </p>
                    <br v-else />
                </div>
            </div>
            <div class="pt-4 border-t border-border">
                <p class="text-xs text-muted-foreground flex items-center gap-1">
                    <UIcon name="i-lucide-sparkles" class="w-3 h-3" />
                    AI-generated insights based on doctor profile
                </p>
            </div>
        </div>

        <div v-if="!insights && !isLoading && !error" class="text-center py-8 text-muted-foreground">
            <UIcon name="i-lucide-sparkles" class="w-12 h-12 mx-auto mb-3 opacity-30" />
            <p className="text-sm">Click "Generate Insights" to get AI-powered analysis</p>
            <p className="text-xs mt-1 opacity-70">Learn why this doctor might be right for you</p>
        </div>
    </div>
</template>
